# A Neural Network in 11 lines of Python 

https://iamtrask.github.io/2015/07/12/basic-python-network/

In [1]:
import numpy as np

# sigmoid function
def nonlin(x, deriv=False):
    if deriv:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

In [2]:
nonlin(0), nonlin(0, deriv=True)

(0.5, 0)

In [3]:
nonlin(-1), nonlin(-1, deriv=True)

(0.2689414213699951, -2)

In [4]:
nonlin(1), nonlin(1, deriv=True)

(0.7310585786300049, 0)

In [5]:
nonlin(-5), nonlin(-5, deriv=True)

(0.0066928509242848554, -30)

In [6]:
nonlin(5), nonlin(5, deriv=True)

(0.99330714907571527, -20)

In [7]:
nonlin(-100), nonlin(-100, deriv=True)

(3.7200759760208356e-44, -10100)

In [8]:
nonlin(100), nonlin(100, deriv=True)

(1.0, -9900)

In [9]:
# input dataset
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

In [16]:
# initialize weights randomly with mean 0
syn0 = 2 * np.random.random((3, 1)) - 1

for iter in xrange(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))

    # how much did we miss?
    l1_error = y - l1
    if iter in [0, 5000, 10000 - 1]:
        print 'Iteration', iter
        print 'L1', l1
        print 'L1 Error', l1_error

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1, True)

    # update weights
    syn0 += np.dot(l0.T, l1_delta)

Iteration 0
L1 [[ 0.27984616]
 [ 0.45289264]
 [ 0.17707083]
 [ 0.31430147]]
L1 Error [[-0.27984616]
 [-0.45289264]
 [ 0.82292917]
 [ 0.68569853]]
Iteration 5000
L1 [[ 0.01377227]
 [ 0.01119784]
 [ 0.99087808]
 [ 0.98877549]]
L1 Error [[-0.01377227]
 [-0.01119784]
 [ 0.00912192]
 [ 0.01122451]]
Iteration 9999
L1 [[ 0.00966474]
 [ 0.00786611]
 [ 0.99358799]
 [ 0.99211921]]
L1 Error [[-0.00966474]
 [-0.00786611]
 [ 0.00641201]
 [ 0.00788079]]


In [11]:
print "Output After Training:"
print l1

Output After Training:
[[ 0.00966449]
 [ 0.00786506]
 [ 0.99358898]
 [ 0.99211957]]


In [12]:
y

array([[0],
       [0],
       [1],
       [1]])

2-layer NN:

In [21]:
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
              [1],
              [1],
              [0]])

In [24]:
# initialize weights randomly with mean 0
syn0 = 2 * np.random.random((3, 4)) - 1
syn1 = 2 * np.random.random((4, 1)) - 1

for j in xrange(60000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))

    # how much did we miss?
    l2_error = y - l2
    
    if j % 10000 == 0:
        print "Error:" + str(np.mean(np.abs(l2_error)))

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1

    l2_delta = l2_error * nonlin(l2, deriv=True)
    
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta = l1_error * nonlin(l1,deriv=True)

    # update weights
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Error:0.498300704492
Error:0.0107355948137
Error:0.00741707962562
Error:0.0059896552968
Error:0.00515020261243
Error:0.00458197289367


In [25]:
print "Output After Training:"
print l2

Output After Training:
[[ 0.00288189]
 [ 0.99587399]
 [ 0.99539408]
 [ 0.00504561]]
